version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:95123574@postgres:5432/dintist_clinic_api?schema=public'
      JWT_SECRET_KEY: 'Ykagva'
      REDIS_URL: 'redis://redis:6379'
      CLOUDINARY_CLOUD_NAME: 'dvouthxyn'
      CLOUDINARY_API_KEY: '171468429772937'
      CLOUDINARY_API_SECRET: '44gzhtdE-BOnkLvCrLxUgCc4_XM'
    command: yarn start
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '95123574'
      POSTGRES_DB: dintist_clinic_api
    ports:
      - 5433:5433
      # - 5432:5432
      # - 5435:5435

    expose:
      - 5433

    # expose:
    #   - 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_volume_data:
